### PR TITLE
feat: support `cl-defun` in namespace macro

### PR DESCRIPTION
**Pull request by JimMoen**
`cl-defun` support for #32 and kosh04/unicode-escape.el#3

### CODE REVIEW

**Comment by JimMoen** [comment]
`cl-defun` support for #32 and kosh04/unicode-escape.el#3

**Comment by JimMoen** [comment]
after this patch:
```elisp
(defalias 'names--convert-cl-defun 'names--convert-defun)
(define-namespace unicode-escape-
(defun* xxx ())
(cl-defun yyy ())
)

(fboundp 'unicode-escape-xxx)           ;=> t
(fboundp 'unicode-escape-yyy)           ;=> t
(fboundp 'yyy)                          ;=> nil
```

**Comment by JimMoen** [comment]
@Malabarba 
Plz review this PR.
Thanks a lot. 🚀

**Comment by Malabarba** [comment]
Thanks for the PR!

**Pull request merged**
