### PR TITLE
Add newer versions of emacs to .travis.yml

### PR DESCRIPTION
**Pull request by davidshepherd7**

### CODE REVIEW

**Comment by Malabarba** [comment]
Thanks for the PR. However, one of the tests needs an extra file to pass. Inside the `tests/elpa/` dir there is a number of autoload files, you need to create one called `aggressive-indent-autoloads-24.4.el` and another for `24.5`.

The point is that these files are the autoloads files you get after installing the package.
I think if you just copy `aggressive-indent-autoloads-24.3.el` the test might pass.

**Comment by davidshepherd7** [comment]
It looks like the failures that are happening now are "real" test failures. In the `dash.el` tests. Is it possible that the version of dash that you have there isn't compatible with 24.4/24.5? I'll look into it after the weekend.

The files `aggressive-indent-autoloads-{24.4,24.5}.el` needed a few changes for those tests to pass. I don't have a very good understanding of what should be in there, so can you take a look to make sure it's ok?

**Comment by Malabarba** [comment]
Yes, the files look ok. These files represent the autoloads file you get when you install aggressive-indent with `package.el`. The reason there's one for each Emacs version is that autoload generation always changes slightly between versions.

The dash failure might just be because the dash version in the tests subdir is a little old. It's hard to say. I'll try to look into it as well when I have some time.

**Comment by davidshepherd7** [comment]
I guess this is dead, I'll close it so it doesn't hang around in my and your open pull requests lists :)

**Comment by Malabarba** [comment]
:+1:

**Pull request closed without merging**
